name: Commit Logger

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate metrics (last 7 days)
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            const runs = await github.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'commit.yml',
              per_page: 1,
            });
            const lastRun = runs.data[0];
            const lastRunDate = lastRun ? new Date(lastRun.created_at) : new Date(0);
            console.log(`Last run date: ${lastRunDate}`);
            const commits = await github.repos.listCommits({
              owner,
              repo,
              since: lastRunDate.toISOString(),
              per_page: 100,
            });
            const commitData = commits.data.map(commit => ({
              date: commit.commit.author.date,
              message: commit.commit.message,
            }));
            const csvLines = commitData.map(c => `"${c.date}","${c.message.replace(/"/g, '""')}"`);
            const csvContent = 'Date,Message\n' + csvLines.join('\n');
            const fs = require('fs');
            fs.writeFileSync('.github/data/commit.csv', csvContent);
      - name: Commit data
        run : |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/data/commit.csv
          git commit -m 'Update commit data' || echo "No changes to commit"
          git push