name: Commit Logger

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write   # needed to push the CSV
  actions: read     # needed to read workflow runs

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics (last 7 days)
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;

            Option B: since last run of a specific workflow file (uncomment to use)
            const { data } = await github.rest.actions.listWorkflowRunsForWorkflow({
               owner,
               repo,
               workflow_id: 'commit.yml',
               per_page: 1
            });
            const lastRun = data.workflow_runs?.[0];
            const lastRunDate = lastRun ? new Date(lastRun.created_at) : new Date(0);

            console.log(`Since: ${lastRunDate.toISOString()}`);

            const commitsResp = await github.rest.repos.listCommits({
              owner,
              repo,
              since: lastRunDate.toISOString(),
              per_page: 100,
            });

            const commitData = (commitsResp.data || []).map(c => ({
              date: c.commit?.author?.date ?? c.commit?.committer?.date ?? '',
              message: (c.commit?.message ?? '').replace(/\r?\n/g, ' '), // flatten newlines
            }));

            const escape = (s) => `"${String(s).replace(/"/g, '""')}"`;
            const csvLines = commitData.map(c => `${escape(c.date)},${escape(c.message)}`);
            const csvContent = 'Date,Message\n' + csvLines.join('\n');

            const fs = require('fs');
            fs.mkdirSync('.github/data', { recursive: true });
            fs.writeFileSync('.github/data/commit.csv', csvContent, 'utf8');

      - name: Commit data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .github/data/commit.csv
          git commit -m 'Update commit data' || echo "No changes to commit"
          git push
